---
tenants:
  - name: ACME
    mac_vrf_vni_base: 10000
    vrfs:
      - name: VRF_C
        vrf_vni: 7777
        mlag_ibgp_peering_vlan: 3777
        svis:
          - id: 101
            name: STAFF_NW
            enabled: true
            ip_address_virtual: 172.16.11.1/24
          - id: 201
            name: MEDIA_NW
            enabled: true
            ip_address_virtual: 172.16.21.1/24
          - id: 301
            name: IOT_NW
            enabled: true
            ip_address_virtual: 172.16.31.1/24
          - id: 401
            name: SALES_NW
            enabled: true
            ip_address_virtual: 172.16.41.1/24
      - name: VRF_S
        vrf_vni: 8888
        mlag_ibgp_peering_vlan: 3888
        svis:
          - id: 20
            name: Internal
            enabled: true
            ip_address_virtual: 10.1.20.1/24
